# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main
variables:
 imageName: 'centos:latest'

pool:
  vmImage: ubuntu-latest

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'
- task: Docker@2
  inputs:
    containerRegistry: 'Docker Hub'
    command: 'pull'
    arguments: $(imageName)
- task: Docker@2
  inputs:
    containerRegistry: 'Aqua Registry'
    command: 'login'
- task: aquasecScanner@4
  inputs:
    image: '$(imageName)'
    scanType: 'local'
    register: false
    hideBase: false
    showNegligible: false
    windowsScannerVersion: '4.2.0'
    scanner: 'registry.aquasec.com/scanner:6.5'
    registry: 'Docker'
    connection: 'AquaScannerSaaS'